version: "2"
services:
  paddle:
    #    build:
    #      context: .
    #      dockerfile: Dockerfile
    #    image: paddle
    image: registry.cn-shenzhen.aliyuncs.com/luler/image_classification
    ports:
      - 5000:5000
    volumes:
      - ./code/api:/root/work
  nginx:
    image: nginx:1.21.6
    ports:
      - 5566:80
    volumes:
      - ./runtime/nginx_logs:/var/log/nginx
      - ./code:/home/wwwroot
      - ./config/nginx/conf.d:/etc/nginx/conf.d
