version: "2"
services:
  nginx:
    image: nginx:1.21.6
    ports:
      - 8000:80
    volumes:
      - ./runtime/nginx_logs:/var/log/nginx
      - ./code:/home/wwwroot
      - ./config/nginx/conf.d:/etc/nginx/conf.d
